### ISSUE TITLE
Exclusive + Required

### ISSUE THREAD

**Issue by ihodes** [alecthomas/voluptuous#115]
I'd love to require exactly one of a few choices, e.g. 

```python
s = Schema({
    Exclusive('project_id', 'project', require=True): Coerce(int), 
    Exclusive('project_name', 'project', require=True): unicode
})
```

(With `require=True` not existing now, but if something like it did, that would be great.)

It's likely this is possible, but I'm not sure how to do it yet. (Is it?)

I'd like `s({})` to fail, for examine, but a schema containing either one of the keys (as is now the case with Exclusive) to pass.

**Comment by svisser** [comment]
I don't think this is currently possible (or at least not well enough documented). As a workaround, you can do the following if the rest of the schema isn't too big to cause duplication:

```python
s = Schema(
    Any(
        {Required('project_id'): Coerce(int)},
        {Required('project_name'): unicode}
    )
)
```

**Comment by ihodes** [comment]
Unfortunately the schema is a bit large for that to work. Right now I'm checking after the schema validates.

**Comment by ihodes** [comment]
Hmm, it seems to me that

```
s = Schema({
    Exclusive('project_id', 'project'): Coerce(int), 
    Exclusive('project_name', 'project'): unicode
}, required=True)
```

ought to exhibit my expected behavior, but it doesn't. 

Would it make sense for me to fix this? I.e. if neither of the exclusive fields are present in the dict, an error should be raised?

**Comment by alecthomas** [comment]
Your example works for me:

```python
>>> from voluptuous import *
>>> s = Schema({
    Exclusive('project_id', 'project'): Coerce(int),
    Exclusive('project_name', 'project'): unicode
}, required=True)
>>> s({'project_id': 1, 'project_name': 'foo'})
MultipleInvalid
Traceback (most recent call last)
...
MultipleInvalid: two or more values in the same group of exclusion 'project'
```

**Comment by svisser** [comment]
@alecthomas it enforces exclusion but it does not enforce the desired behaviour that exactly one key is required:

```
>>> from voluptuous import *
>>> s = Schema({
...     Exclusive('project_id', 'project'): Coerce(int),
...     Exclusive('project_name', 'project'): unicode
... }, required=True)
>>>
>>>
>>> s({})
{}
```

**Comment by alecthomas** [comment]
Ah I see, sorry I missed that. Hmm.

**Comment by kennytrytek-wf** [comment]
@ihodes, you can define your own validator to do that:
```
>>> from voluptuous import *
>>> def has_at_least_one(keys):
...   def f(obj):
...     for k in obj.keys():
...         if k in keys:
...             return obj
...     raise Invalid('Must contain one of {}'.format(keys))
...   return f
... 
>>> keys_schema = has_at_least_one(['project_id', 'project_name'])
>>> exclusive_schema = Schema({
...     Exclusive('project_id', 'project'): Coerce(int),
...     Exclusive('project_name', 'project'): unicode
... }, required=True)
>>> s = All(keys_schema, exclusive_schema)
>>> s({})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kennytrytek/virtualenv/skynet-cli/lib/python2.7/site-packages/voluptuous.py", line 1319, in f
    raise e if msg is None else AllInvalid(msg)
voluptuous.MultipleInvalid: Must contain one of ['project_id', 'project_name']
>>> s({'project_id': 12345})
{'project_id': 12345}
>>> s({'project_name': u'my_project'})
{'project_name': u'my_project'}
>>> s({'project_id': 12345, 'project_name': u'my_project'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kennytrytek/virtualenv/skynet-cli/lib/python2.7/site-packages/voluptuous.py", line 1319, in f
    raise e if msg is None else AllInvalid(msg)
voluptuous.MultipleInvalid: two or more values in the same group of exclusion 'project'
```

**Comment by bcoca** [comment]
Am i misreading http://alecthomas.github.io/voluptuous/docs/_build/html/voluptuous.html#module-voluptuous.schema_builder, it seems like it has an example of that?
```
msg = 'Please, use only one use project_id or project_name.'
schema = Schema({
Exclusive('use_id', 'project', msg=msg):{
    Required('project_idl'): Coerce(int),
    },
Exclusive('use_name', 'project', msg=msg):{
    Required('project_name'): unicode
    },
```

**Comment by kquinsland** [comment]
> Am i misreading http://alecthomas.github.io/voluptuous/docs/_build/html/voluptuous.html#module-voluptuous.schema_builder, it seems like it has an example of that?

@bcoca no, because the key in `Exclusive` becomes required:

```shell
>>> from voluptuous import *
>>> msg = 'Please, only use one: project_id or project_name.'
>>> schema = Schema({
... Exclusive('use_id', 'project', msg=msg):{
...     Required('project_id'): Coerce(int),
...     },
... Exclusive('use_name', 'project', msg=msg):{
...     Required('project_name'): unicode,
...     },
... })
>>> test = {
...     "project_id": 1234
... }
>>> schema(test)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['project_id']
>>> test2 = {"use_id": {"project_id":1234}}
>>> schema(test2)
{'use_id': {'project_id': 1234}}
```

**Comment by bcoca** [comment]
[kquinsland](https://github.com/kquinsland) another developer noted that it only works for subkeys and that 'top level keys' still don't have this function and i just need to create my own.
