### ISSUE TITLE
"AtLeastOne" dict Key Validator

### ISSUE THREAD

**Issue by kennytrytek-wf** [alecthomas/voluptuous#126]
I want to be able to create a Schema with this idea:
```
s = Schema({
    AtLeastOne(
        'onetwo'=Any(1, 2, None),
        'threefour'=Any(3, 4, None)),
    'abc': 'abc'})

>>> s({'abc': 'abc})
AtLeastOneInvalid: Must specify at least one of ['onetwo', 'threefour']
>>> s({'onetwo': 3, 'abc': 'abc})
MultipleInvalid: not a valid value for dictionary value @ data['onetwo']
>>> s({'onetwo': 2, 'abc': 'abc'})
{'onetwo': 2, 'abc': 'abc'}
>>> s({'threefour': 4, 'abc': 'abc'})
{'threefour': 4, 'abc': 'abc'}
>>> s({'onetwo': 1, 'threefour': 3, 'abc': 'abc'})
{'onetwo': 1, 'threefour': 3, 'abc': 'abc'}
```
This completes the functionality started with the addition of `Exclusive` and `Inclusive`.

**Comment by markgollnick-wf** [comment]
This can already be accomplished today with something like the following:

```python
from voluptuous import ALLOW_EXTRA, All, Any, Optional, Required, Schema

key_schema = Schema({
    Required(
        Any('onetwo', 'threefour'),
        msg="Must specify at least one of ['onetwo', 'threefour']"): object
}, extra=ALLOW_EXTRA)

data_schema = Schema({
    Optional('onetwo'): Any(1, 2),
    Optional('threefour'): Any(3, 4),
    'abc': 'abc'
})

s = All(key_schema, data_schema)
```

```
>>> s({'abc': 'abc'})
voluptuous.MultipleInvalid: Must specify at least one of ['onetwo', 'threefour'] @ data[<function Any at 0x1005bb488>]

>>> s({'onetwo': 3, 'abc': 'abc'})
voluptuous.MultipleInvalid: not a valid value for dictionary value @ data['onetwo']

>>> s({'onetwo': 2, 'abc': 'abc'})
{'abc': 'abc', 'onetwo': 2}

>>> s({'threefour': 4, 'abc': 'abc'})
{'abc': 'abc', 'threefour': 4}

>>> s({'onetwo': 1, 'threefour': 3, 'abc': 'abc'})
{'abc': 'abc', 'onetwo': 1, 'threefour': 3}
```

But yes, I like this proposed addition as I think it’s valuable: it would make this kind of construct easier to accomplish, would involve less overhead, and would generally be easier to read and comprehend than what I did above. It would also fill out the following conceptual truth-table quite nicely:

| x | y | class |
| --- | --- | --- |
| if x, *also need* y | if y, *also need* x | Inclusive() — essentially a logical AND or XNOR, depending on whether the keys are required or optional, respectively |
| if x, *can't have* y | if y, *can't have* x | Exclusive() — essentially a logical XOR or NAND, depending on whether the keys are required or optional, respectively |
| if x, *maybe also* y | if y, *maybe also* x | **AtLeastOne() — essentially a logical OR, which, so far as I can tell, isn’t implemented yet** |

The only remaining gate, NOR, I don’t think needs to be worried about: if you don’t want *either* key, just exclude them both from your schema. But I can think of a lot of use cases where having some kind of OR operation requiring at least one of two or more schema keys would be very useful.

**Comment by ironhouzi** [comment]
@markgollnick-wf Could you please show how to get the XOR you mention?  

I've tried: `Required(Exclusive('foo', 'bar')): int)` and `Exclusive(Required('foo'), 'bar'): int`..

**Comment by markgollnick-wf** [comment]
@ironhouzi,

Sorry if I implied that XOR was simple, I realize in hindsight my message was pretty terse and somewhat vague regarding how the other gates work. XOR is actually one of the more difficult ones to accomplish at the moment using vanilla voluptuous features, (even more-so than OR, actually,) since `Exclusive()` specifically denotes an `Optional()` requirement, so getting one or the other of them to behave like a `Required()` takes a little bit of elbow grease. In order to get the desired XOR behavior, you have to link up `Exclusive()` and `Required()` via multiple `Schema()`s using `All()` (see "XOR" below). It's kind of awkward, and I wish there were a better way, (perhaps a `RequiredExclusive()` someday?) but outside of writing a custom validator like you did so that at least it’s reusable, I don’t currently know of any.

For posterity, here's a breakdown of the current status of the "gates" as best as I can work out how voluptuous supports them today:

**Logical AND:**

```python
>>> import voluptuous as v
>>> s = v.Schema({v.Required('a'): object, v.Required('b'): object})
>>> s({})
voluptuous.error.MultipleInvalid: required key not provided @ data['a']
>>> s({'a': 'a'})
voluptuous.error.MultipleInvalid: required key not provided @ data['b']
>>> s({'b': 'b'})
voluptuous.error.MultipleInvalid: required key not provided @ data['a']
>>> s({'a': 'a', 'b': 'b'})
{'a': 'a', 'b': 'b'}
```

**Logical NAND:**

```python
>>> s = v.Schema({v.Exclusive('a', 'NAND'): object, v.Exclusive('b', 'NAND'): object})
>>> s({})
{}
>>> s({'a': 'a'})
{'a': 'a'}
>>> s({'b': 'b'})
{'b': 'b'}
>>> s({'a': 'a', 'b': 'b'})
voluptuous.error.MultipleInvalid: two or more values in the same group of exclusion 'NAND' @ data[<NAND>]
```

**Logical OR:**

```python
>>> s = v.All(
...   v.Schema({v.Required(v.Any('a', 'b')): object}),
...   v.Schema({'a': object, 'b': object}))
>>> 
>>> s({})
voluptuous.error.MultipleInvalid: required key not provided @ data[Any(['a', 'b'])]
>>> s({'a': 'a'})
{'a': 'a'}
>>> s({'b': 'b'})
{'b': 'b'}
>>> s({'a': 'a', 'b': 'b'})
{'a': 'a', 'b': 'b'}
```

**Logical NOR:**

*N/A — don’t include anything in the `Schema()` that’s not needed.*

**Logical XOR:**

```python
>>> s = v.All(
...   v.Any(
...     v.Schema({v.Required('a'): object}, extra=v.ALLOW_EXTRA),
...     v.Schema({v.Required('b'): object}, extra=v.ALLOW_EXTRA)
...   ),
...   v.Schema({
...     v.Exclusive('a', 'XOR'): object,
...     v.Exclusive('b', 'XOR'): object
...   })
... )
>>> s({})
voluptuous.error.MultipleInvalid: required key not provided @ data['a']
>>> s({'a': 'a'})
{'a': 'a'}
>>> s({'b': 'b'})
{'b': 'b'}
>>> s({'a': 'a', 'b': 'b'})
voluptuous.error.MultipleInvalid: two or more values in the same group of exclusion 'XOR' @ data[<XOR>]
```

**Logical XNOR:**

```python
>>> s = v.Schema({v.Inclusive('a', 'XNOR'): object, v.Inclusive('b', 'XNOR'): object})
>>> s({})
{}
>>> s({'a': 'a'})
voluptuous.error.MultipleInvalid: some but not all values in the same group of inclusion 'XNOR' @ data[<XNOR>]
>>> s({'b': 'b'})
voluptuous.error.MultipleInvalid: some but not all values in the same group of inclusion 'XNOR' @ data[<XNOR>]
>>> s({'a': 'a', 'b': 'b'})
{'a': 'a', 'b': 'b'}
```

**Comment by ponsperello90** [comment]
How to validate diferent object in **logical Or**?

Original
```
>>> s = v.All(
...   v.Schema({v.Required(v.Any('a', 'b')): object}),
...   v.Schema({'a': object, 'b': object}))
>>>
 ```

Something like this:
```
>>> s = v.All(
...   v.Schema({v.Required(v.Any('a', 'b')): v.Any({"a1": int}, {"b1": int})}),
...   v.Schema({'a': {"a1": int}, 'b': {"b1": int}}))
>>>
 ```
**a** must contain `{"a1": int},` and **b** must contain `{"b1": int},` but not vice versa

**Comment by markgollnick-wf** [comment]
@ponsperello90, what you have there should work:

```
>>> s = v.All(
...   v.Schema({v.Required(v.Any('a', 'b')): v.Any({"a1": int}, {"b1": int})}),
...   v.Schema({'a': {"a1": int}, 'b': {"b1": int}}))
>>> s({})
voluptuous.error.MultipleInvalid: required key not provided @ data[Any(['a', 'b'])]
>>> s({'a': 'a'})
voluptuous.error.MultipleInvalid: expected a dictionary for dictionary value @ data['a']
>>> s({'a': {'b1': 2}})
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['a']['b1']
>>> s({'a': {'a1': 'a2'}})
voluptuous.error.MultipleInvalid: expected int for dictionary value @ data['a']['a1']
>>> s({'a': {'a1': 1}})
{'a': {'a1': 1}}
>>> s({'b': 'b'})
voluptuous.error.MultipleInvalid: expected a dictionary for dictionary value @ data['b']
>>> s({'b': {'a1': 1}})
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['b']['a1']
>>> s({'b': {'b1': 'b2'}})
voluptuous.error.MultipleInvalid: expected int for dictionary value @ data['b']['b1']
>>> s({'b': {'b1': 2}})
{'b': {'b1': 2}}
>>> s({'a': {'a1': 1}, 'b': {'b1': 2}})
{'a': {'a1': 1}, 'b': {'b1': 2}}
```

However, it can actually be simplified if you take advantage of the fact that voluptuous makes cascaded calls (à la [`reduce()`](https://docs.python.org/2/library/functions.html#reduce)) to each callable passed into `All()` from left to right. In this way, you can use the first clause to assert the correctness of they keys, and lean entirely on the second clause to assert the sanity of the values:

```
>>> s = v.All(
...   v.Schema({v.Required(v.Any('a', 'b')): object}),
...   v.Schema({'a': {'a1': int}, 'b': {'b1': int}}))
>>> s({})
voluptuous.error.MultipleInvalid: required key not provided @ data[Any(['a', 'b'])]
>>> s({'a': 'a'})
voluptuous.error.MultipleInvalid: expected a dictionary for dictionary value @ data['a']
>>> s({'a': {'b1': 2}})
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['a']['b1']
>>> s({'a': {'a1': 'a2'}})
voluptuous.error.MultipleInvalid: expected int for dictionary value @ data['a']['a1']
>>> s({'a': {'a1': 1}})
{'a': {'a1': 1}}
>>> s({'b': 'b'})
voluptuous.error.MultipleInvalid: expected a dictionary for dictionary value @ data['b']
>>> s({'b': {'a1': 1}})
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['b']['a1']
>>> s({'b': {'b1': 'b2'}})
voluptuous.error.MultipleInvalid: expected int for dictionary value @ data['b']['b1']
>>> s({'b': {'b1': 2}})
{'b': {'b1': 2}}
>>> s({'a': {'a1': 1}, 'b': {'b1': 2}})
{'a': {'a1': 1}, 'b': {'b1': 2}}
```

This works because the incoming object is first validated against the `{v.Required(v.Any('a', 'b')): object}` clause, which, so long as it has either `'a'` or `'b'` (or both) top-level keys, will pass; the output is then put through the second clause, which goes one step farther: it demands that the (optional) `'a'` key, if it exists, *must* contain data like `{'a1': int}`; the same goes for the `'b'` key.

Both styles should be equivalent; the latter will just be a hare faster because there will be fewer function calls involved in asserting the data.

**Comment by dbaber** [comment]
@markgollnick-wf How would you do logical implication? Say I have an optional field that if provided must have this other field provided with it. This field by itself also needs to be true.

Bascially I need this:
![image](https://user-images.githubusercontent.com/1522168/29935675-3870aa5e-8e45-11e7-8160-2235601d9609.png)

**Comment by markgollnick-wf** [comment]
@dbaber, In a case like that, I'd probably use two Schemas paired with an `Any()`, one that requires both `p` and `q`, and one that marks `q` as optional (listed in that order, so that validation is attempted against the stricter of the two Schemas first, with the more lenient schema available as a fallback in the event that either `p` or `q` is absent, thus invalidating the payload according to the first Schema):

```python
>>> s = v.Any(
...     v.Schema({v.Required('p'): object, v.Required('q'): object}),
...     v.Schema({v.Optional('q'): object}))
>>> s({})
{}
>>> s({'q': "I'm all alone"})
{'q': "I'm all alone"}
>>> s({'p': "There's no one here beside me"})
MultipleInvalid: required key not provided @ data['q']
>>> s({'p': "My problems have all gone", 'q': "There's no one to deride me"})
{'q': "There's no one to deride me", 'p': 'My problems have all gone'}
```

**Comment by dbaber** [comment]
I was so close.....

**Comment by dbaber** [comment]
What am I doing wrong here?

`# import six
# import voluptuous as v
from voluptuous import (
    ALLOW_EXTRA,
    All,
    Any,
    Coerce,
    Invalid,
    Match,
    Optional,
    Range,
    Required,
    Schema,

)
from functools import wraps

msg = "State is required when rate_center or city is provided"
rate_center_requires_state_schema = Any(
    Schema({
        Required('rate_center'): object,
        Required('state'): object
    }, extra=ALLOW_EXTRA),
    Schema({Optional('state'): object}, extra=ALLOW_EXTRA),
    msg=msg
)
city_requires_state_schema = Any(
    Schema({
        Required('city'): object,
        Required('state'): object
    }, extra=ALLOW_EXTRA),
    Schema({Optional('state'): object}, extra=ALLOW_EXTRA),
    msg=msg
)

base_query_params_schema = Schema(
    {Optional('page'): Coerce(int)}, extra=ALLOW_EXTRA)

area_code_data_schema = Schema(
    {   
        Required('area_code', msg='Area code is required'):
        All(
            str,
            Match(
                r'^[2-9][0-9]{2}$',
                msg="Invalid area code, must be 3 digits with [2-9] for the first digit"
            )   
        ),  

        # TODO: populate rate_center, city, sate (maybe lata) via list of strings from a lookup endpt or DB?

        Optional('rate_center'): str,
        Optional('city'): str,
        Optional('state'): All(str, Match(r'^[A-Z]{2}$')),
        Optional('lata'): All(str, Match(r'^[0-9]{3}$')),
        Required('quantity', default=5000): All(Coerce(int), Range(min=1, max=5000)),
        Optional('group_by'): ['area_code', 'npa_nxx'],
    },  
)

area_code_schema = All(
    base_query_params_schema,
    rate_center_requires_state_schema,
    city_requires_state_schema,
    area_code_data_schema,
)

available_numbers_schema = Any(area_code_schema)`

Hitting `/api/v0/available_numbers/?area_code=262&city=Milwaukee&lata=356`
is not requiring 'sate'. I know this is a bit complicated but it's fronting for a number search via other carriers.

**Comment by dbaber** [comment]
`msg = "State is required when rate_center or city is provided"
rate_center_requires_state_schema = Any(
    Schema({
        Required('rate_center'): object,
        Required('state'): object
    }, extra=ALLOW_EXTRA),
    Schema({Optional('state'): object}, extra=ALLOW_EXTRA),
    msg=msg
)
city_requires_state_schema = Any(
    Schema({
        Required('city'): object,
        Required('state'): object
    }, extra=ALLOW_EXTRA),
    Schema({Optional('state'): object}, extra=ALLOW_EXTRA),
    msg=msg
)

base_query_params_schema = Schema(
    {Optional('page'): Coerce(int)}, extra=ALLOW_EXTRA)

area_code_data_schema = Schema(
    {   
        Required('area_code', msg='Area code is required'):
        All(
            str,
            Match(
                r'^[2-9][0-9]{2}$',
                msg="Invalid area code, must be 3 digits with [2-9] for the first digit"
            )   
        ),  

        # TODO: populate rate_center, city, sate (maybe lata) via list of strings from a lookup endpt or DB?

        Optional('rate_center'): str,
        Optional('city'): str,
        Optional('state'): All(str, Match(r'^[A-Z]{2}$')),
        Optional('lata'): All(str, Match(r'^[0-9]{3}$')),
        Required('quantity', default=5000): All(Coerce(int), Range(min=1, max=5000)),
        Optional('group_by'): ['area_code', 'npa_nxx'],
    },  
)

area_code_schema = All(
    base_query_params_schema,
    rate_center_requires_state_schema,
    city_requires_state_schema,
    area_code_data_schema,
)

available_numbers_schema = Any(area_code_schema)`

**Comment by dbaber** [comment]
@markgollnick-wf It would be nice if examples of this sort of stuff was in the docs :).

**Comment by dbaber** [comment]
@markgollnick-wf I keep running into an issue about extra keys when I try to All() the above with a data schema and once I ALLOW_EXTRA the keys schema fails every time. The key schema does not cover all the keys in the data schema, but allowing extra lets 'p' slip through without a 'q' :(. How would you combine this with a data schema that has more keys than this keys schema?

**Example**
`
city_requires_state_schema = Any(
    Schema({
        Required('city'): object,
        Required('state'): object
    }), 
    Schema({Optional('state'): object}),
    # msg='State is required when city is provided'
)

base_params_schema = Schema({Optional('page'): Coerce(int)})

area_code_params_schema = base_params_schema.extend(
    {   
        Required('area_code', msg='Area code is required'):
        All(
            str,
            Match(
                r'^[2-9][0-9]{2}$',
            ),  
            msg="Invalid area code, must be 3 digits with [2-9] for the first digit"
        ),  

        # TODO: populate rate_center, city, sate (maybe lata) via list of strings from a lookup endpt or DB?

        Optional('rate_center'): str,
        Optional('city'): str,
        Optional('state'): All(str, Match(r'^[A-Z]{2}$')),
        Optional('lata'): All(str, Match(r'^[0-9]{3}$')),
        Required('quantity', default=5000): All(Coerce(int), Range(min=1, max=5000)),
        Optional('group_by'): ['area_code', 'npa_nxx'],
    },  
)

area_code_srch_schema = All(
    # rate_center_requires_state_schema,
    city_requires_state_schema,
    area_code_params_schema,
    # msg='All failed'
)

available_numbers_schema = Any(area_code_srch_schema)
`

**Comment by dbaber** [comment]
A simpler example:
```
>>> import voluptuous as v
>>> s = v.Any(
...     v.Schema({v.Required('p'): object, v.Required('q'): object}),
...     v.Schema({v.Optional('q'): object}))
>>> data_s = v.All(s,
...     v.Schema({v.Optional('p'): str, v.Optional('q'): str, v.Optional('r'): str}))
>>> data_s({'p': 'p'})
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/validators.py", line 264, in __call__
    raise e if self.msg is None else AllInvalid(self.msg)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/validators.py", line 262, in __call__
    v = schema(v)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/schema_builder.py", line 221, in __call__
    return self._compiled([], data)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/schema_builder.py", line 716, in validate_callable
    return schema(data)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/validators.py", line 230, in __call__
    raise error if self.msg is None else AnyInvalid(self.msg)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/validators.py", line 224, in __call__
    return schema(v)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/schema_builder.py", line 221, in __call__
    return self._compiled([], data)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/schema_builder.py", line 716, in validate_callable
    return schema(data)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/schema_builder.py", line 221, in __call__
    return self._compiled([], data)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/schema_builder.py", line 538, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/schema_builder.py", line 370, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: required key not provided @ data['q']
>>> data_s({'p': 'p', 'q': 'q'})
{'q': 'q', 'p': 'p'}
>>> data_s({'q': 'q'})
{'q': 'q'}
>>> data_s({'r': 'r'})
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/validators.py", line 264, in __call__
    raise e if self.msg is None else AllInvalid(self.msg)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/validators.py", line 262, in __call__
    v = schema(v)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/schema_builder.py", line 221, in __call__
    return self._compiled([], data)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/schema_builder.py", line 716, in validate_callable
    return schema(data)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/validators.py", line 230, in __call__
    raise error if self.msg is None else AnyInvalid(self.msg)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/validators.py", line 224, in __call__
    return schema(v)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/schema_builder.py", line 221, in __call__
    return self._compiled([], data)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/schema_builder.py", line 716, in validate_callable
    return schema(data)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/schema_builder.py", line 221, in __call__
    return self._compiled([], data)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/schema_builder.py", line 538, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/home/dbaber/envs/gonzo/lib/python3.5/site-packages/voluptuous/schema_builder.py", line 370, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['r']
>>> 
```

**Comment by dbaber** [comment]
Well, this works...not sure if I like it but it does the job:
```
base_params_schema = Schema({Optional('page'): Coerce(int)})

city_requires_state_schema = Any(
    Schema({
        Required('city'): object,
        Required('state'): object
    }, extra=ALLOW_EXTRA),
    base_params_schema.extend({
        Optional('area_code'): object,
        Optional('rate_center'): object,
        Optional('state'): object,
        Optional('lata'): object,
        Optional('quantity'): object,
        Optional('group_by'): object,
    }), 
    msg='State is required when city is provided'
)

area_code_params_schema = base_params_schema.extend(
    {   
        Required('area_code', msg='Area code is required'):
        All(
            str,
            Match(
                r'^[2-9][0-9]{2}$',
            ),  
            msg="Invalid area code, must be 3 digits with [2-9] for the first digit"
        ),  

        # TODO: populate rate_center, city, sate (maybe lata) via list of strings from a lookup endpt or DB?

        Optional('rate_center'): str,
        Optional('city'): str,
        Optional('state'): All(str, Match(r'^[A-Z]{2}$')),
        Optional('lata'): All(str, Match(r'^[0-9]{3}$')),
        Required('quantity', default=5000): All(Coerce(int), Range(min=1, max=5000)),
        Optional('group_by'): ['area_code', 'npa_nxx'],
    },  
)

area_code_srch_schema = All(
    city_requires_state_schema,
    area_code_params_schema,
)

available_numbers_schema = Any(area_code_srch_schema)
```
