### ISSUE TITLE
missing installation of pandoc when pypandoc is installed fails voluptuous installation

### ISSUE THREAD

**Issue by doodyparizada** [alecthomas/voluptuous#138]
When running my build on Travis requiring latest 0.8.7, I'm getting:
```
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-UHesQn/voluptuous/setup.py", line 14, in <module>
        long_description = pypandoc.convert('README.md', 'rst')
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pypandoc.py", line 19, in convert
        return _convert(_read_file, _process_file, source, to, format, extra_args, encoding=encoding)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pypandoc.py", line 37, in _convert
        from_formats, to_formats = get_pandoc_formats()
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pypandoc.py", line 78, in get_pandoc_formats
        raise OSError("You probably do not have pandoc installed.")
    OSError: You probably do not have pandoc installed.
```

see the solution done here:
https://github.com/bebraw/pypandoc/pull/71/files

**Comment by alecthomas** [comment]
That...is weird. Travis has pypandoc installed, but not pandoc? There is already an ImportError guard around pypandoc. Anyway, fixed.

**Comment by doodyparizada** [comment]
Thanks!
