### ISSUE TITLE
erroneous processing of nested iterables

### ISSUE THREAD

**Issue by jfindlay** [alecthomas/voluptuous#142]
Related to the discussion in https://github.com/alecthomas/voluptuous/pull/141.  See https://github.com/alecthomas/voluptuous/pull/141#issuecomment-167267024 in particular.

Voluptuous seems to get confused by nested iterables.  To demonstrate, I'll use a list of dictionaries.
```pycon
>>> from voluptuous import *
>>> data = [{1: 'one'}, {2: 'two'}]
```

### Case 0: a list of dictionaries
I would expect this to work as is.
```pycon
>>> schema = Schema([{1: str}, {2: str}])
>>> schema(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.4/site-packages/voluptuous.py", line 337, in __call__
    return self._compiled([], data)
  File "/usr/lib64/python3.4/site-packages/voluptuous.py", line 672, in validate_sequence
    cval = validate(index_path, value)
  File "/usr/lib64/python3.4/site-packages/voluptuous.py", line 635, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/lib64/python3.4/site-packages/voluptuous.py", line 471, in validate_mapping
    raise MultipleInvalid(errors)
voluptuous.MultipleInvalid: extra keys not allowed @ data[1][2]
```

### Case 1: the first dictionary has the invalid value
This case correctly finds the true error before getting distracted by the other dictionary.
```pycon
>>> schema = Schema([{1: bool}, {2: str}])
>>> schema(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.4/site-packages/voluptuous.py", line 337, in __call__
    return self._compiled([], data)
  File "/usr/lib64/python3.4/site-packages/voluptuous.py", line 672, in validate_sequence
    cval = validate(index_path, value)
  File "/usr/lib64/python3.4/site-packages/voluptuous.py", line 635, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/lib64/python3.4/site-packages/voluptuous.py", line 471, in validate_mapping
    raise MultipleInvalid(errors)
voluptuous.MultipleInvalid: expected bool for dictionary value @ data[0][1]
```

### Case 2: the second dictionary has the invalid value
Whereas this case does not.
```pycon
>>> schema = Schema([{1: str}, {2: bool}])
>>> schema(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.4/site-packages/voluptuous.py", line 337, in __call__
    return self._compiled([], data)
  File "/usr/lib64/python3.4/site-packages/voluptuous.py", line 672, in validate_sequence
    cval = validate(index_path, value)
  File "/usr/lib64/python3.4/site-packages/voluptuous.py", line 635, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/lib64/python3.4/site-packages/voluptuous.py", line 471, in validate_mapping
    raise MultipleInvalid(errors)
voluptuous.MultipleInvalid: extra keys not allowed @ data[1][2]
```

I will likely try to find time to work on this in the next few days, but if anyone else may know how to fix this, I would be glad for the help.

**Comment by alecthomas** [comment]
Can you try this now that #155 has been merged. I think it may be the same issue.

**Comment by jfindlay** [comment]
This still seems to behave as before.

### update
```console
$ cd .../voluptuous
$ git remote -v
alecthomas      https://github.com/alecthomas/voluptuous.git (fetch)
alecthomas      https://github.com/alecthomas/voluptuous.git (push)
jfindlay        git@github.com:jfindlay/voluptuous.git (fetch)
jfindlay        git@github.com:jfindlay/voluptuous.git (push)
$ git checkout master
$ git fetch alecthomas
remote: Compressing objects: 100% (15/15), done.
remote: Total 54 (delta 28), reused 22 (delta 22), pack-reused 17
Unpacking objects: 100% (54/54), done.
From https://github.com/alecthomas/voluptuous
   314a9f7..5dab7ce  master     -> alecthomas/master
$ git rebase alecthomas/master
First, rewinding head to replay your work on top of it...
Fast-forwarded master to alecthomas/master.
```
### version, data
```py
$ python2
Python 2.7.10 (default, Nov 20 2015, 16:09:58)
[GCC 4.9.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import voluptuous
>>> voluptuous.__version__
'0.8.9'
>>> from voluptuous import *
>>> data = [{1: 'one'}, {2: 'two'}]
```
### Case 0
```py
>>> schema = Schema([{1: str}, {2: str}])
>>> schema(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "voluptuous.py", line 351, in __call__
    return self._compiled([], data)
  File "voluptuous.py", line 688, in validate_sequence
    cval = validate(index_path, value)
  File "voluptuous.py", line 651, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "voluptuous.py", line 485, in validate_mapping
    raise MultipleInvalid(errors)
voluptuous.MultipleInvalid: extra keys not allowed @ data[1][2]
```
### Case 1
```py
>>> schema = Schema([{1: bool}, {2: str}])
>>> schema(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "voluptuous.py", line 351, in __call__
    return self._compiled([], data)
  File "voluptuous.py", line 688, in validate_sequence
    cval = validate(index_path, value)
  File "voluptuous.py", line 651, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "voluptuous.py", line 485, in validate_mapping
    raise MultipleInvalid(errors)
voluptuous.MultipleInvalid: expected bool for dictionary value @ data[0][1]
```
### Case 2
```py
>>> schema = Schema([{1: str}, {2: bool}])
>>> schema(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "voluptuous.py", line 351, in __call__
    return self._compiled([], data)
  File "voluptuous.py", line 688, in validate_sequence
    cval = validate(index_path, value)
  File "voluptuous.py", line 651, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "voluptuous.py", line 485, in validate_mapping
    raise MultipleInvalid(errors)
voluptuous.MultipleInvalid: extra keys not allowed @ data[1][2]
```

**Comment by Tankanow** [comment]
I'm running into this issue too.

## Version

```bash
> pip list | grep voluptuous
voluptuous              0.11.5
```

## Reproduction

```python
>>> from voluptuous import Schema
>>> ll = [[1], [2]]
>>> Schema(ll)(ll)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test.py", line 10, in <module>
  File "lib/python3.6/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "lib/python3.6/site-packages/voluptuous/schema_builder.py", line 630, in validate_sequence
    cval = validate(index_path, value)
  File "lib/python3.6/site-packages/voluptuous/schema_builder.py", line 641, in validate_sequence
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: not a valid value @ data[1][0]
```

## Cause

I believe the problem is here: https://github.com/alecthomas/voluptuous/blob/2e557f71db6260e3ab40a6848a6bf4705d434f2d/voluptuous/schema_builder.py#L633

This `for validate in _compiled` loop is actually applying the *every* validator in the `_compiled` sequence to each item in the sequence, instead of just the validator at the proper index to the item at the same index.

### Confirmation

If all of the subsequences have the same schema, then this validator works.

```python
>>> ll = [[1], [1]]  # <-- All subsequences are same
>>> Schema(ll)(ll)
[[1], [1]]
```

## Resolution

I have not had time to come up with a satisfactory solution yet. If this is still a popular issue, I'll try to find some time to fix this in the near future.

**Comment by alecthomas** [comment]
> This for validate in _compiled loop is actually applying every validator in the _compiled sequence to each item in the sequence, instead of just the validator at the proper index to the item at the same index.

That's the documented behaviour, see the section on [lists](https://github.com/alecthomas/voluptuous#lists). ie. each element is a candidate.

To the broader issue, I'm going to say that this is not a bug as voluptuous deliberately does not do backtracking for builtin collections. To achieve the behaviour you want, use `Any()`. eg.

```python
>>> schema = Schema([Any({1:str}, {2:str})])
>>> data = [{1: 'one'}, {2: 'two'}]
>>> schema(data)
[{1: 'one'}, {2: 'two'}]
```

**Comment by Tankanow** [comment]
Ah ... thanks @alecthomas, I should RTFM. 😉 

I _do_ think a concatenation of predicates applied to ordered sequences _is_ valuable, a la [Clojure Spec](https://clojure.org/about/spec#_sequences)'s`cat` operator. Is this possible?

**Comment by alecthomas** [comment]
Yes, you want [ExactSequence](https://alecthomas.github.io/voluptuous/docs/_build/html/voluptuous.html#voluptuous.validators.ExactSequence).
