### ISSUE TITLE
When validating a sub-schema against possible schemas, the error messages are not correct

### ISSUE THREAD

**Issue by mprager** [alecthomas/voluptuous#214]
Say you have something like this:

```
import voluptuous as v
s = v.Schema([v.Any({v.Required('a'): 3}, {v.Required('b'):4})])
```

this means that you expect a list of elements, each element can either be a dictionary with key 'a' and value 3, or a dictionary with key 'b' and value 4.

The validation works:

```
>>> s = v.Schema([v.Any({v.Required('a'): 3}, {v.Required('b'):4})])
>>> s([{'a':3}])
[{'a': 3}]
>>> s([{'b':4}])
[{'b': 4}]
```

however when you violate it the message you get does not make sense:
```
>>> s([{'b':3}])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mprager/.virtualenv/validator/lib/python2.7/site-packages/voluptuous/schema_builder.py", line 192, in __call__
    return self._compiled([], data)
  File "/home/mprager/.virtualenv/validator/lib/python2.7/site-packages/voluptuous/schema_builder.py", line 523, in validate_sequence
    cval = validate(index_path, value)
  File "/home/mprager/.virtualenv/validator/lib/python2.7/site-packages/voluptuous/schema_builder.py", line 625, in validate_callable
    return schema(data)
  File "/home/mprager/.virtualenv/validator/lib/python2.7/site-packages/voluptuous/validators.py", line 230, in __call__
    raise error if self.msg is None else AnyInvalid(self.msg)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data[0]['b']
```

The message should read like:
```
voluptuous.error.MultipleInvalid: not a valid value for dictionary value @ data[0]['b']
```

For more complex validation, this makes it hard for the user to know what exactly is wrong with the schema.

**Comment by mprager** [comment]
In the original comment, there was a list of schema, but this issue is the same without. 

```
s = v.Schema(v.Any({v.Required('a'): 3}, {v.Required('b'):4}))
>>> s({'a': 3})
{'a': 3}
>>> s({'b': 4})
{'b': 4}
>>> s({'b': 3})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mprager/.virtualenv/validator/lib/python2.7/site-packages/voluptuous/schema_builder.py", line 192, in __call__
    return self._compiled([], data)
  File "/home/mprager/.virtualenv/validator/lib/python2.7/site-packages/voluptuous/schema_builder.py", line 625, in validate_callable
    return schema(data)
  File "/home/mprager/.virtualenv/validator/lib/python2.7/site-packages/voluptuous/validators.py", line 230, in __call__
    raise error if self.msg is None else AnyInvalid(self.msg)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['b']
```

**Comment by alecthomas** [comment]
MultipleInvalid contains all errors (including the one you want), but only reports the first one encountered. There is no way for it to know which error to report in a situation like this, and in fact whichever one it chooses will be wrong in some situation:

```python
>>> s = v.Schema(v.Any({v.Required('a'): 3}, {v.Required('b'):4}, int, basestring))
>>> s(1.2)
MultipleInvalid: expected a dictionary
```

What should Any report in this situation? There's no way to know, so Voluptuous errs on the side of simplicity, preserves the rest, but allows you to customise the error message:

```python
>>> s = v.Schema(v.Any({v.Required('a'): 3}, {v.Required('b'):4}, int, basestring,
    msg="expected {'a': 3}, {'b': 4}, int or string"))
>>> s(1.2)
MultipleInvalid: expected {'a': 3}, {'b': 4}, int or string
```

**Comment by mprager** [comment]
That makes perfect sense, I guess my expected output would rely on some
kind of metric for what the "closest" schema. That is overly complex for
this application and would probably lead to unexpected behavior anyways.

I'll use the msg keyword.

Thanks, I find this library much cleaner than others which accomplish a
similar purpose.
Mike
