### ISSUE TITLE
MultipleInvalid error reporting path is unpredictable

### ISSUE THREAD

**Issue by warsaw** [alecthomas/voluptuous#239]
I've been trying to debug an unpredictable failure in some of my code, which I'll attach.  Sometimes when I run this I get the following traceback:

```
% python3 bug.py
Traceback (most recent call last):
  File "bug.py", line 201, in <module>
    main()
  File "bug.py", line 198, in main
    GadgetYAML(yaml)
  File "/usr/lib/python3/dist-packages/voluptuous/schema_builder.py", line 192, in __call__
    return self._compiled([], data)
  File "/usr/lib/python3/dist-packages/voluptuous/schema_builder.py", line 486, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/lib/python3/dist-packages/voluptuous/schema_builder.py", line 324, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['volumes']['first-image']['structure'][0]['content'][0]['offset-write']
```

Other times I get this traceback:

```
% python3 bug.py
Traceback (most recent call last):
  File "bug.py", line 201, in <module>
    main()
  File "bug.py", line 198, in main
    GadgetYAML(yaml)
  File "/usr/lib/python3/dist-packages/voluptuous/schema_builder.py", line 192, in __call__
    return self._compiled([], data)
  File "/usr/lib/python3/dist-packages/voluptuous/schema_builder.py", line 486, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/lib/python3/dist-packages/voluptuous/schema_builder.py", line 324, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['volumes']['first-image']['structure'][0]['content'][0]['image']
```

Notice that the path reported is different.  You may have to run the script multiple times to see the difference as it appears to be completely random.  I don't *think* it's related to PYTHONHASHSEED since the randomness is still present when I explicitly set PYTHONHASHSEED.

Ubuntu 16.10; Python 3.5.2+; voluptuous 0.9.3

**Comment by warsaw** [comment]
Apologies for the length of this example.  It's as boiled down as I've been able to get it so far.

```
import re

from enum import Enum
from operator import methodcaller
from uuid import UUID
from voluptuous import Any, Coerce, Match, Optional, Required, Schema
from yaml import load


class GadgetSpecificationError(Exception):
    """An exception occurred during the parsing of the gadget.yaml file."""


def straight_up_bytes(count):
    return count


def MiB(count):
    return count * 2**20


def GiB(count):
    return count * 2**30


def as_size(size, min=0, max=None):
    # Check for int-ness and just return what you get if so.  YAML parsers
    # will turn values like '108' into ints automatically, but voluptuous will
    # always try to coerce the value to an as_size.
    if isinstance(size, int):
        value = size
    else:
        mo = re.match('(\d+)([a-zA-Z]*)', size)
        if mo is None:
            raise ValueError(size)
        size_in_bytes = mo.group(1)
        value = {
            '': straight_up_bytes,
            'G': GiB,
            'M': MiB,
            }[mo.group(2)](int(size_in_bytes))
    if max is None:
        if value < min:
            raise ValueError('Value outside range: {} < {}'.format(value, min))
    elif not (min <= value < max):
        raise ValueError('Value outside range: {} <= {} < {}'.format(
            min, value, max))
    return value


class BootLoader(Enum):
    uboot = 'u-boot'
    grub = 'grub'


class VolumeSchema(Enum):
    mbr = 'mbr'
    gpt = 'gpt'


class FileSystemType(Enum):
    none = 'none'
    ext4 = 'ext4'
    vfat = 'vfat'


class Enumify:
    def __init__(self, enum_class, msg=None, preprocessor=None):
        self.enum_class = enum_class
        self.preprocessor = preprocessor

    def __call__(self, v):
        # Turn KeyErrors into spec errors.
        try:
            return self.enum_class[
                v if self.preprocessor is None
                else self.preprocessor(v)
                ]
        except KeyError as error:
            raise GadgetSpecificationError(
                "Invalid gadget.yaml value '{}' @ {}".format(
                    v, self.enum_class.yaml_path))


def Size32bit(v):
    """Coerce size to being a 32 bit integer."""
    return as_size(v, max=GiB(4))


def Id(v):
    """Coerce to either a hex UUID, a 2-digit hex value."""
    if isinstance(v, int):
        # Okay, here's the problem.  If the id value is something like '80' in
        # the yaml file, the yaml parser will turn that into the decimal
        # integer 80, but that's really not what we want!  We want it to be
        # the hex value 0x80.  So we have to turn it back into a string and
        # allow the 2-digit validation matcher to go from there.
        if v >= 100 or v < 0:
            raise ValueError(str(v))
        v = '{:02d}'.format(v)
    try:
        return UUID(hex=v)
    except ValueError:
        pass
    mo = re.match('^[a-fA-F0-9]{2}$', v)
    if mo is None:
        raise ValueError(v)
    return mo.group(0).upper()


def HybridId(v):
    """Like above, but allows for hybrid Ids."""
    if isinstance(v, str):
        code, comma, guid = v.partition(',')
        if comma == ',':
            # Two digit hex code must appear before GUID.
            if len(code) != 2 or len(guid) != 36:
                raise ValueError(v)
            hex_code = Id(code)
            guid_code = Id(guid)
            return hex_code, guid_code
    return Id(v)


def RelativeOffset(v):
    """From the spec:

    It may be specified relative to another structure item with the
    syntax ``label+1234``.
    """
    label, plus, offset = v.partition('+')
    if len(label) == 0 or plus != '+' or len(offset) == 0:
        raise ValueError(v)
    return label, Size32bit(offset)


GadgetYAML = Schema({
    Optional('defaults'): {
        Match('^[a-zA-Z0-9]+$'): {
            Match('^[-a-zA-Z0-9]+$'): object
        }
    },
    Optional('device-tree-origin', default='gadget'): str,
    Optional('device-tree'): str,
    Required('volumes'): {
        Match('^[-a-zA-Z0-9]+$'): Schema({
            Optional('schema', default=VolumeSchema.gpt):
                Enumify(VolumeSchema),
            Optional('bootloader'): Enumify(
                BootLoader, preprocessor=methodcaller('replace', '-', '')),
            Optional('id'): Coerce(Id),
            Required('structure'): [Schema({
                Optional('name'): str,
                Optional('offset'): Coerce(as_size),
                Optional('offset-write'): Any(
                    Coerce(Size32bit), RelativeOffset),
                Required('size'): Coerce(as_size),
                Required('type'): Any('mbr', Coerce(HybridId)),
                Optional('id'): Coerce(UUID),
                Optional('filesystem', default=FileSystemType.none):
                    Enumify(FileSystemType),
                Optional('filesystem-label'): str,
                Optional('content'): Any(
                    [Schema({
                        Required('source'): str,
                        Required('target'): str,
                        })
                    ],                                  # noqa: E124
                    [Schema({
                        Required('image'): str,
                        Optional('offset'): Coerce(as_size),
                        Optional('offset-write'): Any(
                            Coerce(Size32bit), RelativeOffset),
                        Optional('size'): Coerce(as_size),
                        })
                    ],
                )
            })]
        })
    }
})


def main():
    data = """\
volumes:
  first-image:
    schema: gpt
    bootloader: u-boot
    structure:
        - type: 00000000-0000-0000-0000-0000deadbeef
          size: 400M
          content:
          - image: foo.img
            offset-write: 4G
"""
    yaml = load(data)
    GadgetYAML(yaml)


main()
```

**Comment by warsaw** [comment]
Note that I would always and only expect 'offset-write' in the error since '4G' does not fit in 32 bits, but never 'image' since that accepts any string.

**Comment by elipavlov** [comment]
If you ask 'Why different errors occurring', then may be it happens because of dicts in Python interpreter (until version 3.6) was not sorted by default, during voluptuous  processing dict raise exception on the first field which was found

**Comment by warsaw** [comment]
Please note that even in Python 3.6, built-in dicts are **not** guaranteed to be sorted.  You cannot count on that implementation detail.  The only guarantees are that [keyword argument dicts](https://www.python.org/dev/peps/pep-0468) (i.e. `**kws`) and [class dictionaries](https://www.python.org/dev/peps/pep-0520) are ordered.  It is explicitly the case that the ordering semantics of built-in dictionary has not changed.  IOW, if you need ordered dicts, use [collections.OrderedDict](https://docs.python.org/3/library/collections.html#collections.OrderedDict).

https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep520

**Comment by alecthomas** [comment]
@warsaw that's exactly what @elipavlov 's point was ... he's suggesting the error reporting differs based on which dict key is validated first. I would say this is almost certainly the case, and I wouldn't really consider it a bug.

**Comment by alecthomas** [comment]
Unless you're saying that your 'image' key should not ever be reporting an error...which reading in more detail, seems to be the case.
