### ISSUE TITLE
Incorrect error messages when using subschemas inside a list?

### ISSUE THREAD

**Issue by ThatsGobbles** [alecthomas/voluptuous#284]
I'm seeing some unexpected error messages when using subschemas inside a list.

I've made a simple test case that illustrates what I'm seeing. I'm using the following Schema:

```python
test = Schema([Any({Required('text'): str}, {Required('num'): int})])
```

And the invocations that show unexpected error messages are:

```python
test([{}]) # Message says that the required 'text' key is missing, but no mention of 'num'
test([{'num': 'hello!'}]) # Message says that extra keys are not allowed??
# Note that test([{'text': 27}]) returns an error message I'd expect
```

```python
>>> from voluptuous import Schema, Any, Required
>>> test = Schema([Any({Required('text'): str}, {Required('num'): int})])

>>> test([])
[]

>>> test([{}])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 221, in __call__
    return self._compiled([], data)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 575, in validate_sequence
    cval = validate(index_path, value)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 716, in validate_callable
    return schema(data)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/validators.py", line 230, in __call__
    raise error if self.msg is None else AnyInvalid(self.msg)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/validators.py", line 224, in __call__
    return schema(v)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 221, in __call__
    return self._compiled([], data)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 538, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 370, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: required key not provided @ data[0]['text']

>>> test([{'text': 'hello!'}])
[{'text': 'hello!'}]

>>> test([{'text': 27}])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 221, in __call__
    return self._compiled([], data)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 575, in validate_sequence
    cval = validate(index_path, value)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 716, in validate_callable
    return schema(data)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/validators.py", line 230, in __call__
    raise error if self.msg is None else AnyInvalid(self.msg)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/validators.py", line 224, in __call__
    return schema(v)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 221, in __call__
    return self._compiled([], data)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 538, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 370, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected str for dictionary value @ data[0]['text']

>>> test([{'num': 27}])
[{'num': 27}]

>>> test([{'num': 'hello!'}])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 221, in __call__
    return self._compiled([], data)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 575, in validate_sequence
    cval = validate(index_path, value)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 716, in validate_callable
    return schema(data)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/validators.py", line 230, in __call__
    raise error if self.msg is None else AnyInvalid(self.msg)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/validators.py", line 224, in __call__
    return schema(v)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 221, in __call__
    return self._compiled([], data)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 538, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/home/lemoine/venvs/cheffu/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 370, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data[0]['num']
```

Is this a bug, or am I using the library incorrectly?

**Comment by ThatsGobbles** [comment]
Seems to be the same issue as #142

**Comment by svisser** [comment]
There is some more discussion about this last year: https://github.com/alecthomas/voluptuous/issues/114.

**Comment by tusharmakkar08** [comment]
Closing this as it is similar to #142
