### ISSUE TITLE
cannot have module named error and util in my project

### ISSUE THREAD

**Issue by lonsdale8734** [alecthomas/voluptuous#310]
I cannot name a module `error` in my project. Here is the exception message.

```
Traceback (most recent call last):
  File "xxx/python3.6/site-packages/voluptuous/__init__.py", line 4, in <module>
    from schema_builder import *
ModuleNotFoundError: No module named 'schema_builder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/src/main.py", line 20, in <module>
    __register_blueprint(app)
  File "/src/main.py", line 10, in __register_blueprint
    import view.timetable
  File "/src/view/timetable.py", line 5, in <module>
    from form import timetable as timetable_form
  File "/src/form/timetable.py", line 3, in <module>
    from voluptuous import Schema, Required, Length, Range, All
  File "xxx/python3.6/site-packages/voluptuous/__init__.py", line 10, in <module>
    from .validators import *
  File "xxx/python3.6/site-packages/voluptuous/validators.py", line 110, in <module>
    @message('value was not true', cls=TrueInvalid)
  File "xxx/python3.6/site-packages/voluptuous/schema_builder.py", line 1103, in message
    if cls and not issubclass(cls, er.Invalid):
AttributeError: module 'error' has no attribute 'Invalid'
```

When I deep into the code, I found the reason is that voluptuous used relative import

```
try:
    from schema_builder import *
    from validators import *
    from util import *
    from error import *
except ImportError:
    from .schema_builder import *
    from .validators import *
    from .util import *
    from .error import *

__version__ = '0.10.5'
__author__ = 'tusharmakkar08'
```

**Comment by tusharmakkar08** [comment]
Hey @lonsdale8734 

Thanks for reporting the issue. I am a little busy right now, Can you fix the issue and create a corresponding PR? I will review it and get it merged. 

Thanks.

**Comment by tusharmakkar08** [comment]
Ok. We'll release the new version soon. Closing this issue for now.
