### ISSUE TITLE
Date validator fails if len(input_string) != 10

### ISSUE THREAD

**Issue by entropiae** [alecthomas/voluptuous#339]
The Date validator always check if the length of the input string is equal to the length of the default format string (10); however this conditions may be (incorrectly) not verified when a custom format string is supplied and the input string respect this format.

Example:
```
>>> validators.Date('%Y%d%m')('20180101')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rcirimelli/.local/share/virtualenvs/feed_normalizer-ROQHSXxK/lib/python3.6/site-packages/voluptuous/validators.py", line 645, in __call__
    ' expected length %d (%s)' % (len(self.FORMAT_DESCRIPTION), self.FORMAT_DESCRIPTION))
voluptuous.error.DateInvalid: value has invalid length expected length 10 (yyyy-mm-dd)
>>>
>>> datetime.datetime.strptime('20180101', '%Y%d%m')
datetime.datetime(2018, 1, 1, 0, 0)
```

**Comment by alecthomas** [comment]
Ah. Yes that seems like a bug, a PR would be welcome.

**Comment by entropiae** [comment]
I would be happy to provide a PR for it; it's ok if I remove the check altogether? As far as I know, there's no way to compute the len of the string-to-be-validated from the format string.

**Comment by alecthomas** [comment]
Yes I think that will be fine. I suspect it was leftover from before the Date validator allowed formatting (perhaps)...
