### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'required'

### ISSUE THREAD

**Issue by greypanda** [alecthomas/voluptuous#404]
I just installed the most recent esphome and it is now broken. I'm running Ubuntu 18.04.3, but it also fails on Debian. 

Here is the failure:

Traceback (most recent call last):
  File "/home/manager/.local/bin/esphome", line 7, in <module>
    from esphome.__main__ import main
  File "/home/manager/.local/lib/python2.7/site-packages/esphome/__main__.py", line 10, in <module>
    from esphome import const, writer, yaml_util
  File "/home/manager/.local/lib/python2.7/site-packages/esphome/writer.py", line 7, in <module>
    from esphome.config import iter_components
  File "/home/manager/.local/lib/python2.7/site-packages/esphome/config.py", line 15, in <module>
    from esphome import core, core_config, yaml_util
  File "/home/manager/.local/lib/python2.7/site-packages/esphome/core_config.py", line 6, in <module>
    import esphome.config_validation as cv
  File "/home/manager/.local/lib/python2.7/site-packages/esphome/config_validation.py", line 1242, in <module>
    Optional(CONF_COMMAND_TOPIC): All(requires_component('mqtt'), subscribe_topic),
  File "/home/manager/.local/lib/python2.7/site-packages/esphome/voluptuous_schema.py", line 198, in extend
    ret = super(_Schema, self).extend(schema, extra=extra)
  File "/home/manager/.local/lib/python2.7/site-packages/voluptuous/schema_builder.py", line 782, in extend
    return result_cls(result, required=result_required, extra=result_extra)
TypeError: __init__() got an unexpected keyword argument 'required'

I was able to get it working again by removing "required=result_required" from line 782.

**Comment by alecthomas** [comment]
You should report this to esphome then?

**Comment by greypanda** [comment]
I have done that. It's just tourist info for you, I guess.
